= Run containers and build images

. *Run your first Docker container* - This section will show how to use the workflow explained earlier to run a container. The following switches will be explained: `-it`, `-d`, `-P`, `-p`.
. *Run container* - This section will explain the following switches for running containers `-v`, `-env`, `-cpu`, `-m`.
. *Build your first image* - This section will introducte the concept of Dockerfile. The following instructions will be covered `FROM`, `CMD`, `RUN`, `ADD`/`COPY`.
. *Build your image* - This section will explain the following instruction for building an image `USER`, `EXPOSE`, `ENTRYPOINT`.
. *Build your image* - This section will explain how `HEALTHCHECK` instruction can be specified to enable health check of containers. `docker run` command will be shown to overrride the command.
. *Build your first Docker image*
.. Build context
.. `apt-get update`
.. `docker build`
. *Push/run your image to/from Docker Hub*
.. `docker build -t`
.. `latest`
.. Private registry
.. Build your image and debug the layout
