= Introduction

. *Introduction to Docker* - This section will introduce what is Docker. It'll explain the three key concepts of Build, Ship and Run with Docker. The fundamentals of Image and Container will be introduced.
.. Application Delivery Technology
.. Build, Ship, Run
.. Image
.. Container
. *Docker Workflow* - This section will explain the workflow of Docker. You'll learn how a client, host and hub work together for a typical lifecycle.
.. Client, Host, Hub
. *Getting Started with Docker* - This section will explain how to get started with Docker on Mac, Windows and Linux. Difference between Experimental and Stable will be explained.
.. `yum install` or `apt-get install`
. *Getting Started with Docker Toolbox* - This section will explain how to use Docker Toolbox to get started. Connecting to the default Docker Machine will be explained. A new Docker Machine will be created and how to connect to it will be explained.
.. Different components
.. Docker Machine
.. Show how to connect with default Docker Machine
.. Create a new Docker Machine and connect to it
.. `-d` driver
